default_language_version:
    python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: ^.*\.(md|rst)$
    - id: debug-statements
    - id: mixed-line-ending
    - id: check-merge-conflict

  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
      types: [python]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.2
    hooks:
    - id: isort
